### ISSUE TITLE
bbox file is not available

### ISSUE THREAD

**Issue by JIANG-KING** [MitchFuchs/ChimpBehave#1]
The bbox file in the dataset you provided is a soft link file, not a real file. Could you provide the original file?
![1729218760624](https://github.com/user-attachments/assets/19ec1945-361d-4f6c-86cf-2a880cf57f12)

**Comment by MitchFuchs** [comment]
HI @JIANG-KING, 

Thanks for your interest and your comment. Please find the original files at: https://drive.google.com/file/d/1RYp11Gj1jdU9KssIqqT8GBzX9lrCITuT/view?usp=sharing 

Let me know if that works OK for you. 

Cheers, 
Mitch

**Comment by JIANG-KING** [comment]
Thank you very much for the bbox file, it is very useful
